name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: <your-aws-region>
  ECR_REPOSITORY: <your-ecr-repository-name>

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/your-ecr-repository:${{ github.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update LightSail container service
      run: |
        aws lightsail update-container-service --service-name <your-lightsail-service-name> --public-endpoint '{"containerName":"<your-container-name>","containerPort":80}'
        aws lightsail push-container-image --service-name <your-lightsail-service-name> --label <your-lightsail-container-label> --image-and-tag ${{ steps.login-ecr.outputs.registry }}/your-ecr-repository:${{ github.sha }}
