name: Deploy Workout App to Amazon ECR and Lightsail

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: operation-stacked-auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workout-app code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/operation-stacked-auth:latest

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Update container-service.json with the new image
      run: |
        # Update the container-service.json file with the new image URL for workout-container
        # You can use a tool like jq or a script to perform the update

    - name: Deploy to Lightsail Container Service
      run: |
        aws lightsail create-container-service-deployment \
          --service-name operation-stacked \
          --containers file://containers.json

