name: Deploy Workout App to Amazon ECR and Lightsail

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: operation-stacked-auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workout-app code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/operation-stacked-auth:latest

    - name: Update container-service.json with the new image
      run: |
        # Update the container-service.json file with the new image URL for workout-container
        # You can use a tool like jq or a script to perform the update

    - name: Set AWS credentials as environment variables
      run: |
        echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "export AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    - name: SSH into EC2 and deploy new container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Stop and remove the existing container
          sudo docker stop operation-stacked-auth
          sudo docker rm operation-stacked-auth

          # Pull the latest image from ECR
          sudo docker pull 108546418244.dkr.ecr.eu-west-2.amazonaws.com/operation-stacked-auth:latest

          # Start the new container
          sudo docker run -d -p 5001:80 \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
          --name operation-stacked-auth \
          108546418244.dkr.ecr.eu-west-2.amazonaws.com/operation-stacked-auth:latest
